DELETE FROM TRADES;
DELETE FROM ORDERS;
DELETE FROM SECURITIES;
DELETE FROM USERS;

-- FOREIGN KEYS
ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_SECURITIES
FOREIGN KEY (ORD_SEC_ID)
REFERENCES SECURITIES(SEC_ID)
ON UPDATE SET NULL
ON DELETE SET NULL;

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_USERS
FOREIGN KEY (ORD_USR_ID)
REFERENCES USERS(USR_ID)
ON UPDATE SET NULL
ON DELETE SET NULL;

ALTER TABLE TRADES
ADD CONSTRAINT FK_TRADES_ORDERS_BUY
FOREIGN KEY (TRD_ORD_BUY_ID)
REFERENCES ORDERS(ORD_ID)
ON UPDATE SET NULL
ON DELETE SET NULL;

ALTER TABLE TRADES
ADD CONSTRAINT FK_TRADES_ORDERS_SELL
FOREIGN KEY (TRD_ORD_SELL_ID)
REFERENCES ORDERS(ORD_ID)
ON UPDATE SET NULL
ON DELETE SET NULL;

-- ORDERS.ORD_TYPE ONLY ADMITS BUY OR SELL
ALTER TABLE ORDERS
ADD CONSTRAINT CK_ORD_TYPE_BUY_SELL
CHECK (ORD_TYPE IN ('BUY', 'SELL'));

-- PRICE AND QUANTITY COLUMNS HIGHER THAN 0
ALTER TABLE ORDERS
ADD CONSTRAINT CK_ORD_PRICE_HIGHER0
CHECK (ORD_PRICE > 0);

ALTER TABLE ORDERS
ADD CONSTRAINT CK_ORD_QUANTITY_HIGHER0
CHECK (ORD_QUANTITY > 0);

ALTER TABLE TRADES
ADD CONSTRAINT CK_TRD_PRICE_HIGHER0
CHECK (TRD_PRICE > 0);

ALTER TABLE TRADES
ADD CONSTRAINT CK_TRD_QUANTITY_HIGHER0
CHECK (TRD_QUANTITY > 0);